name: Packages

on:
  workflow_dispatch:

jobs:

  build-libs-android:

    name: Build libs (Android)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: 🐼 Setup go1.22
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install NDK
      run: |
        wget -q https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
        unzip -q android-ndk-r26d-linux.zip
        echo "ANDROID_NDK_HOME=$(pwd)/android-ndk-r26d" >> $GITHUB_ENV
        echo "NDK_ROOT=$(pwd)/android-ndk-r26d" >> $GITHUB_ENV
  
    - name: Run build command
      run: |
        echo $ANDROID_NDK_HOME
        # First get and install the specific versions
        go get golang.org/x/mobile@v0.0.0-20240520174638-fa72addaaa1b
        go get golang.org/x/mobile/cmd/gobind@v0.0.0-20240520174638-fa72addaaa1b
        go get golang.org/x/mobile/cmd/gomobile@v0.0.0-20240520174638-fa72addaaa1b

        # Use a version that's compatible with Go 1.22
        go install golang.org/x/mobile/cmd/gomobile@v0.0.0-20240520174638-fa72addaaa1b
        go install golang.org/x/mobile/cmd/gobind@v0.0.0-20240520174638-fa72addaaa1b

        gomobile init
        ./contrib/mobile/build -a
    
    - name: Get version
      id: get_version
      run: |
        PKGVERSION=$(sh -c './contrib/semver/version.sh --bare') 
        echo "PKGVERSION=$PKGVERSION" >> $GITHUB_ENV

    - name: Upload .aar files
      uses: actions/upload-artifact@v4
      with:
        name: aar-files
        path: '**/*.aar'

    - name: Upload .jar files
      uses: actions/upload-artifact@v4
      with:
        name: jar-files
        path: '**/*.jar'
    
    - name: Publish aar library to Maven repo
      uses: RiV-chain/copy-local-file-maven-action@main
      with:
        artifact_repo: RiV-chain/artifact
        artifact_path: mesh.aar
        artifact_source_path: mesh-sources.jar
        gh_pat: ${{ secrets.MAVEN_PAT }}
        artifact_id: v6space
        group_id: org.rivchain
        version: ${{ env.PKGVERSION }}